Attribute VB_Name = "Module1"
Public zdrw As Boolean
Public sjkz As Boolean
Public zdd As Boolean
Public audd As Boolean
Public ksmss As Boolean
Public thm As String
Public lskb As String
Public lszr As String
Public nzr As String
Public aud As String
Public dt As String
Public disk As Integer
Public dskop As Integer
Public fricls As Integer
Public speed As Integer
Public speedd As Integer
Public lleft As Integer
Public toumd As Integer
Public tmdu As Integer
Public tomd As Single
Public sspeed As Long
Public n As Integer
Public ystime As Integer
Public ystext As String
Public cdspeed As Integer
Public maxl As Integer
Public maxt As Integer
Public x As Integer
Public y As Integer
